# Generated by Django 3.2.12 on 2022-10-08 11:02

from django.db import migrations, models
import django.db.models.deletion
import shorten.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', shorten.fields.URLField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=6, max_length=32, prefix='', unique=True)),
                ('long_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_url', to='shorten.url')),
            ],
        ),
    ]
