# Generated by Django 3.2.16 on 2022-10-14 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_auto_20221009_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(choices=[('SAF', 'Safari'), ('CHR', 'Chrome'), ('OPE', 'Opera'), ('FOX', 'Firefox'), ('EDG', 'Edge'), ('IEX', 'Internet Explorer'), ('UCB', 'UC Browser'), ('O', 'Other')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('browser_name', models.CharField(choices=[('SAF', 'Safari'), ('CHR', 'Chrome'), ('OPE', 'Opera'), ('FOX', 'Firefox'), ('EDG', 'Edge'), ('IEX', 'Internet Explorer'), ('UCB', 'UC Browser'), ('O', 'Other')], max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='num_clicks',
            new_name='num_visits',
        ),
        migrations.DeleteModel(
            name='Click',
        ),
        migrations.AddField(
            model_name='visit',
            name='short_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', related_query_name='visit', to='shorten.shorturl'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='browser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortened_urls', related_query_name='shortened_url', to='shorten.browser'),
        ),
    ]
