# Generated by Django 3.2.16 on 2022-10-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0004_auto_20221014_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browser',
            name='name',
            field=models.CharField(choices=[('CHR', 'Chrome'), ('OPE', 'Opera'), ('FOX', 'Firefox'), ('EDG', 'Edge'), ('IEX', 'Internet Explorer'), ('SAF', 'Safari'), ('UCB', 'UC Browser'), ('O', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser_name',
            field=models.CharField(choices=[('CHR', 'Chrome'), ('OPE', 'Opera'), ('FOX', 'Firefox'), ('EDG', 'Edge'), ('IEX', 'Internet Explorer'), ('SAF', 'Safari'), ('UCB', 'UC Browser'), ('O', 'Other')], max_length=3),
        ),
    ]
