# Generated by Django 3.2.16 on 2022-10-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0005_auto_20221015_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='browser',
        ),
        migrations.AlterField(
            model_name='browser',
            name='name',
            field=models.CharField(choices=[('CHR', 'Chrome'), ('OPR', 'Opera'), ('FOX', 'Firefox'), ('EDG', 'Edge'), ('IEX', 'Internet Explorer'), ('SAF', 'Safari'), ('UCB', 'UC Browser'), ('O', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser_name',
            field=models.CharField(choices=[('CHR', 'Chrome'), ('OPR', 'Opera'), ('FOX', 'Firefox'), ('EDG', 'Edge'), ('IEX', 'Internet Explorer'), ('SAF', 'Safari'), ('UCB', 'UC Browser'), ('O', 'Other')], max_length=3),
        ),
        migrations.CreateModel(
            name='BrowserSavedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shorten.browser')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shorten.url')),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='browsers',
            field=models.ManyToManyField(blank=True, related_name='urls', related_query_name='url', through='shorten.BrowserSavedURL', to='shorten.Browser'),
        ),
        migrations.AddConstraint(
            model_name='browsersavedurl',
            constraint=models.UniqueConstraint(fields=('browser', 'url'), name='unique_browser_saved_url'),
        ),
    ]
