# Generated by Django 3.2.16 on 2022-10-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0006_auto_20221015_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browsersavedurl',
            old_name='data',
            new_name='date',
        ),
    ]
