# Generated by Django 3.2.16 on 2022-10-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0007_rename_data_browsersavedurl_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='browsers',
        ),
        migrations.AddField(
            model_name='browser',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='browsers', related_query_name='browser', through='shorten.ShortURL', to='shorten.URL'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='browser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_urls', related_query_name='short_url', to='shorten.browser'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='short_urls', related_query_name='short_url', to='shorten.url'),
        ),
        migrations.DeleteModel(
            name='BrowserSavedURL',
        ),
    ]
